# Generated by Django 5.1.3 on 2025-04-02 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='daate_of_birth',
            new_name='date_of_birth',
        ),
    ]
