# Generated by Django 5.1.3 on 2025-04-07 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0003_rename_daate_of_birth_player_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standing',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.team'),
        ),
    ]
