# Generated by Django 5.1.3 on 2025-04-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0004_alter_standing_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standing',
            name='form',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
