# Generated by Django 5.2 on 2025-04-29 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0008_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScheduledTask',
        ),
    ]
